import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { LightSwitchComponent } from './light-switch.component';

describe('LightSwitchComponent', () => {
    
    // autogenerated code
    let component: LightSwitchComponent;
    let fixture: ComponentFixture<LightSwitchComponent>;

    // FROM DOCUMENTATION:
    /* You can ignore this section if you only run tests with the CLI ng test command because the CLI compiles the application before running the tests.
    */
    /* 
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [ LightSwitchComponent ]
        })
        .compileComponents();
    }));
   */

    beforeEach(() => {
        fixture = TestBed.createComponent(LightSwitchComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it('should create', () => {
        expect(component).toBeTruthy();
    });

    // I added this code
    it('#switched should toggle #isOn', () => {
        const comp = new LightSwitchComponent()
        expect(comp.isOn).toBe(false, 'off at first')
        comp.switchLight()
        expect(comp.isOn).toBe(true, 'on after switched')
        comp.switchLight()
        expect(comp.isOn).toBe(false, 'off after second switch')
    })

    it('#switchLight should set #message "on" after click', () => {
        const comp = new LightSwitchComponent()
        expect(comp.message).toMatch('off', 'off at first')
        comp.switchLight()
        expect(comp.message).toMatch('on', 'on after switched')
    })
});
