import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { DashboardHeroComponent } from './dashboard-hero.component';
import { Hero } from '../interfaces';
/* DashboardHeroComponent appears within the template of a parent component, which binds a hero to the @Input property and listens for an event raised through the selected @Output property.

You can test that the class code works without creating the DashboardHeroComponent or its parent component.
*/

describe('DashboardHeroComponent', () => {
    // autogenerated code
    let component: DashboardHeroComponent;
    let fixture: ComponentFixture<DashboardHeroComponent>;

    // everything works even if this piece of code is commented out
    // FROM DOCUMENTATION:
    /* You can ignore this section if you only run tests with the CLI ng test command because the CLI compiles the application before running the tests.
    */
    /* 
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [ DashboardHeroComponent ]
        }).compileComponents();
    }));
 */
    beforeEach(() => {
        fixture = TestBed.createComponent(DashboardHeroComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it('should create', () => {
        expect(component).toBeTruthy();
    });

    // I added this code
    it('raised the selected event when clicked', () => {
        const comp = new DashboardHeroComponent
        const hero:Hero = {id:123, name:'Test'}
        comp.hero = hero
        comp.selected.subscribe( (selectedHero:Hero) => expect(selectedHero).toBe(hero))
        comp.click()
    })

});
